# Generated by Django 3.2 on 2021-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('number', models.IntegerField(verbose_name='تعداد افراد')),
                ('phone', models.IntegerField(verbose_name='شماره تلفن')),
                ('time', models.TimeField(verbose_name='زمان')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('occasion', models.CharField(max_length=300, verbose_name='مناسبت')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزورها',
            },
        ),
    ]
