# Generated by Django 3.2 on 2021-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseve',
            name='date',
            field=models.CharField(max_length=300, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='reseve',
            name='number',
            field=models.CharField(max_length=300, verbose_name='تعداد افراد'),
        ),
        migrations.AlterField(
            model_name='reseve',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='reseve',
            name='time',
            field=models.CharField(max_length=300, verbose_name='زمان'),
        ),
    ]
