# Generated by Django 3.2 on 2021-05-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20210509_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseve',
            name='date',
            field=models.DateField(max_length=300, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='reseve',
            name='time',
            field=models.TimeField(max_length=300, verbose_name='زمان'),
        ),
    ]
