# Generated by Django 3.2 on 2021-05-04 16:56

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام غذا')),
                ('price', models.IntegerField(max_length=100, verbose_name='قمیت')),
                ('body', models.TextField(max_length=250, verbose_name='توضیح کوتاه در باره غذا')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
