# Generated by Django 3.2 on 2021-05-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Special_today',
            field=models.BooleanField(default=False, verbose_name='مخصوص امروز'),
        ),
    ]
