# Generated by Django 3.2 on 2021-05-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_time_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='time_food',
        ),
    ]
