# Generated by Django 3.2 on 2021-05-16 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_products_time_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='time_food',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
